#!/bin/bash
# Setup script for mkcert - generates locally-trusted SSL certificates
# Run this ONCE on your host machine to get rid of certificate warnings
#
# More info: https://words.filippo.io/mkcert-valid-https-certificates-for-localhost/

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CERTS_DIR="${SCRIPT_DIR}/certs"

# Load SERVER_NAME from site.env
source "${SCRIPT_DIR}/srcs/nginx/site.env" 2>/dev/null || true
SERVER_NAME="${SERVER_NAME:-transcendance}"

echo "=== mkcert SSL Certificate Setup ==="
echo ""

# Check if mkcert is installed
if ! command -v mkcert &> /dev/null; then
    echo "mkcert is not installed. Installing..."
    
    # Detect OS and install
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Check if we're on WSL
        if grep -qi microsoft /proc/version 2>/dev/null; then
            echo "Detected WSL environment"
        fi
        
        # Try different package managers
        if command -v apt-get &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y libnss3-tools
            # Download mkcert binary
            MKCERT_VERSION="v1.4.4"
            sudo curl -L "https://github.com/FiloSottile/mkcert/releases/download/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64" -o /usr/local/bin/mkcert
            sudo chmod +x /usr/local/bin/mkcert
        elif command -v brew &> /dev/null; then
            brew install mkcert nss
        else
            echo "Please install mkcert manually: https://github.com/FiloSottile/mkcert#installation"
            exit 1
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        if command -v brew &> /dev/null; then
            brew install mkcert nss
        else
            echo "Please install Homebrew first, then run: brew install mkcert nss"
            exit 1
        fi
    else
        echo "Unsupported OS. Please install mkcert manually: https://github.com/FiloSottile/mkcert#installation"
        exit 1
    fi
fi

echo "mkcert version: $(mkcert -version 2>/dev/null || mkcert --version)"

# Install the local CA (this makes browsers trust mkcert certificates)
echo ""
echo "Installing local CA into system trust store..."
echo "This will make your browser trust certificates generated by mkcert."
mkcert -install

# Create certificates directory
mkdir -p "${CERTS_DIR}"

# Generate certificates for the server
echo ""
echo "Generating certificates for: ${SERVER_NAME}, localhost, 127.0.0.1"
cd "${CERTS_DIR}"

# Generate the certificate - mkcert creates files named after the first domain
mkcert -key-file "${SERVER_NAME}.key" -cert-file "${SERVER_NAME}.crt" \
    "${SERVER_NAME}" \
    "localhost" \
    "127.0.0.1" \
    "::1"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Certificates generated in: ${CERTS_DIR}"
ls -la "${CERTS_DIR}"
echo ""
echo "The certificates are now trusted by your system/browser."
echo ""
echo "Next steps:"
echo "  1. Rebuild nginx: docker compose build nginx"
echo "  2. Restart the stack: docker compose up -d"
echo ""
echo "If you're on WSL and using a Windows browser, you may also need to:"
echo "  1. Copy the root CA to Windows: cp \"\$(mkcert -CAROOT)/rootCA.pem\" /mnt/c/Users/YOUR_USER/"
echo "  2. Double-click the rootCA.pem in Windows and install it to 'Trusted Root Certification Authorities'"
