{
 "title": "Pong Metrics",
 "tags": [
  "pong",
  "app",
  "nodejs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pong - Event Loop Lag (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pong_nodejs_eventloop_lag_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pong - CPU (rate of process_cpu_seconds_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pong_process_cpu_seconds_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pong - Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pong_process_resident_memory_bytes/1024/1024",
     "legendFormat": "resident MB - {{instance}}"
    },
    {
     "expr": "pong_process_heap_bytes/1024/1024",
     "legendFormat": "heap MB - {{instance}}"
    },
    {
     "expr": "pong_process_virtual_memory_bytes/1024/1024",
     "legendFormat": "virtual MB - {{instance}}"
    }
   ]
  }
 ]
}